import { Component, OnInit } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';
import { InternationalizationService } from '../services/internationalization.service';
export interface Country {
  code: string;
  viewValue: string;
}
@Component({
  selector: 'app-complete-profile',
  templateUrl: './complete-profile.component.html',
  styleUrls: ['./complete-profile.component.css']
})


export class CompleteProfileComponent implements OnInit {
  ngOnInit() {
    
  }
  constructor(public translate: TranslateService) {

    translate.use(localStorage.getItem('lang') !== null || localStorage.getItem('lang') !== null ? localStorage.getItem('lang') : 'en');

  }
  countries: Country[] = [

    { viewValue: 'Afghanistan', code: 'AF' },
    { viewValue: 'land Islands', code: 'AX' },
    { viewValue: 'Albania', code: 'AL' },
    { viewValue: 'Algeria', code: 'DZ' },
    { viewValue: 'American Samoa', code: 'AS' },
    { viewValue: 'AndorrA', code: 'AD' },
    { viewValue: 'Angola', code: 'AO' },
    { viewValue: 'Anguilla', code: 'AI' },
    { viewValue: 'Antarctica', code: 'AQ' },
    { viewValue: 'Antigua and Barbuda', code: 'AG' },
    { viewValue: 'Argentina', code: 'AR' },
    { viewValue: 'Armenia', code: 'AM' },
    { viewValue: 'Aruba', code: 'AW' },
    { viewValue: 'Australia', code: 'AU' },
    { viewValue: 'Austria', code: 'AT' },
    { viewValue: 'Azerbaijan', code: 'AZ' },
    { viewValue: 'Bahamas', code: 'BS' },
    { viewValue: 'Bahrain', code: 'BH' },
    { viewValue: 'Bangladesh', code: 'BD' },
    { viewValue: 'Barbados', code: 'BB' },
    { viewValue: 'Belarus', code: 'BY' },
    { viewValue: 'Belgium', code: 'BE' },
    { viewValue: 'Belize', code: 'BZ' },
    { viewValue: 'Benin', code: 'BJ' },
    { viewValue: 'Bermuda', code: 'BM' },
    { viewValue: 'Bhutan', code: 'BT' },
    { viewValue: 'Bolivia', code: 'BO' },
    { viewValue: 'Bosnia and Herzegovina', code: 'BA' },
    { viewValue: 'Botswana', code: 'BW' },
    { viewValue: 'Bouvet Island', code: 'BV' },
    { viewValue: 'Brazil', code: 'BR' },
    { viewValue: 'British Indian Ocean Territory', code: 'IO' },
    { viewValue: 'Brunei Darussalam', code: 'BN' },
    { viewValue: 'Bulgaria', code: 'BG' },
    { viewValue: 'Burkina Faso', code: 'BF' },
    { viewValue: 'Burundi', code: 'BI' },
    { viewValue: 'Cambodia', code: 'KH' },
    { viewValue: 'Cameroon', code: 'CM' },
    { viewValue: 'Canada', code: 'CA' },
    { viewValue: 'Cape Verde', code: 'CV' },
    { viewValue: 'Cayman Islands', code: 'KY' },
    { viewValue: 'Central African Republic', code: 'CF' },
    { viewValue: 'Chad', code: 'TD' },
    { viewValue: 'Chile', code: 'CL' },
    { viewValue: 'China', code: 'CN' },
    { viewValue: 'Christmas Island', code: 'CX' },
    { viewValue: 'Cocos (Keeling) Islands', code: 'CC' },
    { viewValue: 'Colombia', code: 'CO' },
    { viewValue: 'Comoros', code: 'KM' },
    { viewValue: 'Congo', code: 'CG' },
    { viewValue: 'Congo, The Democratic Republic of the', code: 'CD' },
    { viewValue: 'Cook Islands', code: 'CK' },
    { viewValue: 'Costa Rica', code: 'CR' },
    { viewValue: 'Cote D"Ivoire', code: 'CI' },
    { viewValue: 'Croatia', code: 'HR' },
    { viewValue: 'Cuba', code: 'CU' },
    { viewValue: 'Cyprus', code: 'CY' },
    { viewValue: 'Czech Republic', code: 'CZ' },
    { viewValue: 'Denmark', code: 'DK' },
    { viewValue: 'Djibouti', code: 'DJ' },
    { viewValue: 'Dominica', code: 'DM' },
    { viewValue: 'Dominican Republic', code: 'DO' },
    { viewValue: 'Ecuador', code: 'EC' },
    { viewValue: 'Egypt', code: 'EG' },
    { viewValue: 'El Salvador', code: 'SV' },
    { viewValue: 'Equatorial Guinea', code: 'GQ' },
    { viewValue: 'Eritrea', code: 'ER' },
    { viewValue: 'Estonia', code: 'EE' },
    { viewValue: 'Ethiopia', code: 'ET' },
    { viewValue: 'Falkland Islands (Malvinas)', code: 'FK' },
    { viewValue: 'Faroe Islands', code: 'FO' },
    { viewValue: 'Fiji', code: 'FJ' },
    { viewValue: 'Finland', code: 'FI' },
    { viewValue: 'France', code: 'FR' },
    { viewValue: 'French Guiana', code: 'GF' },
    { viewValue: 'French Polynesia', code: 'PF' },
    { viewValue: 'French Southern Territories', code: 'TF' },
    { viewValue: 'Gabon', code: 'GA' },
    { viewValue: 'Gambia', code: 'GM' },
    { viewValue: 'Georgia', code: 'GE' },
    { viewValue: 'Germany', code: 'DE' },
    { viewValue: 'Ghana', code: 'GH' },
    { viewValue: 'Gibraltar', code: 'GI' },
    { viewValue: 'Greece', code: 'GR' },
    { viewValue: 'Greenland', code: 'GL' },
    { viewValue: 'Grenada', code: 'GD' },
    { viewValue: 'Guadeloupe', code: 'GP' },
    { viewValue: 'Guam', code: 'GU' },
    { viewValue: 'Guatemala', code: 'GT' },
    { viewValue: 'Guernsey', code: 'GG' },
    { viewValue: 'Guinea', code: 'GN' },
    { viewValue: 'Guinea-Bissau', code: 'GW' },
    { viewValue: 'Guyana', code: 'GY' },
    { viewValue: 'Haiti', code: 'HT' },
    { viewValue: 'Heard Island and Mcdonald Islands', code: 'HM' },
    { viewValue: 'Holy See (Vatican City State)', code: 'VA' },
    { viewValue: 'Honduras', code: 'HN' },
    { viewValue: 'Hong Kong', code: 'HK' },
    { viewValue: 'Hungary', code: 'HU' },
    { viewValue: 'Iceland', code: 'IS' },
    { viewValue: 'India', code: 'IN' },
    { viewValue: 'Indonesia', code: 'ID' },
    { viewValue: 'Iran, Islamic Republic Of', code: 'IR' },
    { viewValue: 'Iraq', code: 'IQ' },
    { viewValue: 'Ireland', code: 'IE' },
    { viewValue: 'Isle of Man', code: 'IM' },
    { viewValue: 'Israel', code: 'IL' },
    { viewValue: 'Italy', code: 'IT' },
    { viewValue: 'Jamaica', code: 'JM' },
    { viewValue: 'Japan', code: 'JP' },
    { viewValue: 'Jersey', code: 'JE' },
    { viewValue: 'Jordan', code: 'JO' },
    { viewValue: 'Kazakhstan', code: 'KZ' },
    { viewValue: 'Kenya', code: 'KE' },
    { viewValue: 'Kiribati', code: 'KI' },
    { viewValue: 'Korea, Democratic People"S Republic of', code: 'KP' },
    { viewValue: 'Korea, Republic of', code: 'KR' },
    { viewValue: 'Kuwait', code: 'KW' },
    { viewValue: 'Kyrgyzstan', code: 'KG' },
    { viewValue: 'Lao People"S Democratic Republic', code: 'LA' },
    { viewValue: 'Latvia', code: 'LV' },
    { viewValue: 'Lebanon', code: 'LB' },
    { viewValue: 'Lesotho', code: 'LS' },
    { viewValue: 'Liberia', code: 'LR' },
    { viewValue: 'Libyan Arab Jamahiriya', code: 'LY' },
    { viewValue: 'Liechtenstein', code: 'LI' },
    { viewValue: 'Lithuania', code: 'LT' },
    { viewValue: 'Luxembourg', code: 'LU' },
    { viewValue: 'Macao', code: 'MO' },
    { viewValue: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
    { viewValue: 'Madagascar', code: 'MG' },
    { viewValue: 'Malawi', code: 'MW' },
    { viewValue: 'Malaysia', code: 'MY' },
    { viewValue: 'Maldives', code: 'MV' },
    { viewValue: 'Mali', code: 'ML' },
    { viewValue: 'Malta', code: 'MT' },
    { viewValue: 'Marshall Islands', code: 'MH' },
    { viewValue: 'Martinique', code: 'MQ' },
    { viewValue: 'Mauritania', code: 'MR' },
    { viewValue: 'Mauritius', code: 'MU' },
    { viewValue: 'Mayotte', code: 'YT' },
    { viewValue: 'Mexico', code: 'MX' },
    { viewValue: 'Micronesia, Federated States of', code: 'FM' },
    { viewValue: 'Moldova, Republic of', code: 'MD' },
    { viewValue: 'Monaco', code: 'MC' },
    { viewValue: 'Mongolia', code: 'MN' },
    { viewValue: 'Montenegro', code: 'ME' },
    { viewValue: 'Montserrat', code: 'MS' },
    { viewValue: 'Morocco', code: 'MA' },
    { viewValue: 'Mozambique', code: 'MZ' },
    { viewValue: 'Myanmar', code: 'MM' },
    { viewValue: 'Namibia', code: 'NA' },
    { viewValue: 'Nauru', code: 'NR' },
    { viewValue: 'Nepal', code: 'NP' },
    { viewValue: 'Netherlands', code: 'NL' },
    { viewValue: 'Netherlands Antilles', code: 'AN' },
    { viewValue: 'New Caledonia', code: 'NC' },
    { viewValue: 'New Zealand', code: 'NZ' },
    { viewValue: 'Nicaragua', code: 'NI' },
    { viewValue: 'Niger', code: 'NE' },
    { viewValue: 'Nigeria', code: 'NG' },
    { viewValue: 'Niue', code: 'NU' },
    { viewValue: 'Norfolk Island', code: 'NF' },
    { viewValue: 'Northern Mariana Islands', code: 'MP' },
    { viewValue: 'Norway', code: 'NO' },
    { viewValue: 'Oman', code: 'OM' },
    { viewValue: 'Pakistan', code: 'PK' },
    { viewValue: 'Palau', code: 'PW' },
    { viewValue: 'Palestinian Territory, Occupied', code: 'PS' },
    { viewValue: 'Panama', code: 'PA' },
    { viewValue: 'Papua New Guinea', code: 'PG' },
    { viewValue: 'Paraguay', code: 'PY' },
    { viewValue: 'Peru', code: 'PE' },
    { viewValue: 'Philippines', code: 'PH' },
    { viewValue: 'Pitcairn', code: 'PN' },
    { viewValue: 'Poland', code: 'PL' },
    { viewValue: 'Portugal', code: 'PT' },
    { viewValue: 'Puerto Rico', code: 'PR' },
    { viewValue: 'Qatar', code: 'QA' },
    { viewValue: 'Reunion', code: 'RE' },
    { viewValue: 'Romania', code: 'RO' },
    { viewValue: 'Russian Federation', code: 'RU' },
    { viewValue: 'RWANDA', code: 'RW' },
    { viewValue: 'Saint Helena', code: 'SH' },
    { viewValue: 'Saint Kitts and Nevis', code: 'KN' },
    { viewValue: 'Saint Lucia', code: 'LC' },
    { viewValue: 'Saint Pierre and Miquelon', code: 'PM' },
    { viewValue: 'Saint Vincent and the Grenadines', code: 'VC' },
    { viewValue: 'Samoa', code: 'WS' },
    { viewValue: 'San Marino', code: 'SM' },
    { viewValue: 'Sao Tome and Principe', code: 'ST' },
    { viewValue: 'Saudi Arabia', code: 'SA' },
    { viewValue: 'Senegal', code: 'SN' },
    { viewValue: 'Serbia', code: 'RS' },
    { viewValue: 'Seychelles', code: 'SC' },
    { viewValue: 'Sierra Leone', code: 'SL' },
    { viewValue: 'Singapore', code: 'SG' },
    { viewValue: 'Slovakia', code: 'SK' },
    { viewValue: 'Slovenia', code: 'SI' },
    { viewValue: 'Solomon Islands', code: 'SB' },
    { viewValue: 'Somalia', code: 'SO' },
    { viewValue: 'South Africa', code: 'ZA' },
    { viewValue: 'South Georgia and the South Sandwich Islands', code: 'GS' },
    { viewValue: 'Spain', code: 'ES' },
    { viewValue: 'Sri Lanka', code: 'LK' },
    { viewValue: 'Sudan', code: 'SD' },
    { viewValue: 'Suriname', code: 'SR' },
    { viewValue: 'Svalbard and Jan Mayen', code: 'SJ' },
    { viewValue: 'Swaziland', code: 'SZ' },
    { viewValue: 'Sweden', code: 'SE' },
    { viewValue: 'Switzerland', code: 'CH' },
    { viewValue: 'Syrian Arab Republic', code: 'SY' },
    { viewValue: 'Taiwan, Province of China', code: 'TW' },
    { viewValue: 'Tajikistan', code: 'TJ' },
    { viewValue: 'Tanzania, United Republic of', code: 'TZ' },
    { viewValue: 'Thailand', code: 'TH' },
    { viewValue: 'Timor-Leste', code: 'TL' },
    { viewValue: 'Togo', code: 'TG' },
    { viewValue: 'Tokelau', code: 'TK' },
    { viewValue: 'Tonga', code: 'TO' },
    { viewValue: 'Trinidad and Tobago', code: 'TT' },
    { viewValue: 'Tunisia', code: 'TN' },
    { viewValue: 'Turkey', code: 'TR' },
    { viewValue: 'Turkmenistan', code: 'TM' },
    { viewValue: 'Turks and Caicos Islands', code: 'TC' },
    { viewValue: 'Tuvalu', code: 'TV' },
    { viewValue: 'Uganda', code: 'UG' },
    { viewValue: 'Ukraine', code: 'UA' },
    { viewValue: 'United Arab Emirates', code: 'AE' },
    { viewValue: 'United Kingdom', code: 'GB' },
    { viewValue: 'United States', code: 'US' },
    { viewValue: 'United States Minor Outlying Islands', code: 'UM' },
    { viewValue: 'Uruguay', code: 'UY' },
    { viewValue: 'Uzbekistan', code: 'UZ' },
    { viewValue: 'Vanuatu', code: 'VU' },
    { viewValue: 'Venezuela', code: 'VE' },
    { viewValue: 'Viet Nam', code: 'VN' },
    { viewValue: 'Virgin Islands, British', code: 'VG' },
    { viewValue: 'Virgin Islands, U.S.', code: 'VI' },
    { viewValue: 'Wallis and Futuna', code: 'WF' },
    { viewValue: 'Western Sahara', code: 'EH' },
    { viewValue: 'Yemen', code: 'YE' },
    { viewValue: 'Zambia', code: 'ZM' },
    { viewValue: 'Zimbabwe', code: 'ZW' }

  ];

}
